# src/maxson_build_utils/scaffold/packaging/buildozer.py
from __future__ import annotations

from pathlib import Path
import os
import shutil

from ...helpers import WriteResult, write_str_to_file
from ...names import to_title_case
from ...pyproject import MaxsonPyProject
from ...context import PACKAGE_DIR, PROJECT_ROOT

BUILDOZER_SPEC_TEMPLATE = """\
# This .spec config file tells Buildozer an app's requirements for being built.
#
# It is generated by maxson-build-utils.
# Edit this file for Buildozer-specific packaging requirements.

[app]

# (str) Title of your application
title = {APP_TITLE}

# (str) Package name
package.name = {PACKAGE_NAME}

# (str) Package domain (needed for Android/iOS packaging)
package.domain = {PACKAGE_DOMAIN}

# (str) Source code where the main.py lives
source.dir = ../../

# (list) Source files to include
source.include_exts = py,png,jpg,kv,atlas,whl,wsdl,json

# (list) Source files to include using pattern matching
source.include_patterns = src/*,vendor_for_buildozer/*
#source.include_patterns = ./src/*,./build/vendor-wheels/

# (list) Source directories to exclude
source.exclude_dirs = tests,bin,.git,.venv,.pytest_cache,docs,logs,packaging

# (list) Source patterns to exclude
source.exclude_patterns = Dockerfile*,build_*.py,package.py,daemon_*.py

# (str) Application version
version = {VERSION}

# (list) Application requirements
#
# Keep this deliberately small. Dependencies that do not have
# Buildozer/python-for-android recipes can be vendored separately.
requirements = hostpython3==3.11.9,python3==3.11.9,kivy,pyjnius

# (str) Presplash
# presplash.filename = %(source.dir)s/data/presplash.png

# (str) Icon
# icon.filename = %(source.dir)s/src/{IMPORT_NAME}/data/icons/placeholder.png

# (str) Orientation
orientation = portrait

# (bool) Whether to fullscreen
fullscreen = 0


[buildozer]

# (int) Log level (0 = error only, 1 = info, 2 = debug (with command output))
log_level = 2

# (int) Display warning if buildozer is run as root (0 = False, 1 = True)
warn_on_root = 1

# (str) Path to build artifact storage, absolute or relative to spec file
# build_dir = ../../build/buildozer/
build_dir = ~/.buildozer_work/{IMPORT_NAME}/build/
# (str) Path to build output (i.e. .apk, .aab, .ipa) storage
bin_dir = ../../dist/buildozer/



# (str) Warning: Buildozer configuration can be extended here as needed.
"""


def resolve_buildozer_metadata(
    path: Path | str | None = None,
) -> dict[str, str]:
    pyproject = MaxsonPyProject(path)

    import_name = pyproject.import_name
    app_name = pyproject.app_name

    package_name = (
        pyproject.get(
            "tool",
            "maxson-build-utils",
            "buildozer",
            "package-name",
        )
        or import_name
    )

    base_domain = pyproject.get(
        "tool",
        "maxson-build-utils",
        "buildozer",
        "package-domain",
    ) or "com.memphis_wastewater"

    package_domain = f"{base_domain}.{package_name}"

    version = (
        pyproject.get(
            "project",
            "version",
        )
        or "0.1"
    )

    return {
        "APP_TITLE": to_title_case(app_name),
        "PACKAGE_NAME": package_name,
        "PACKAGE_DOMAIN": package_domain,
        "IMPORT_NAME": import_name,
        "VERSION": version,
    }

def copy_source_dunder_main_to_root_main_for_buildozer_entry_point(
    overwrite: bool | None = False,
) -> None:
    """Copies the package __main__.py to project root main.py for Buildozer entrypoint."""
    if overwrite is None:
        env_val = os.getenv("BUILDOZER_MAIN_COPY_OVERWRITE", "false").lower()
        overwrite = env_val in ("1", "true", "yes")

    source_filepath = PACKAGE_DIR / "__main__.py"
    dst_filepath = PROJECT_ROOT / "main.py"

    if source_filepath.exists():
        if not dst_filepath.exists() or overwrite:
            shutil.copyfile(source_filepath, dst_filepath)


def run_init_buildozer(
    root_dir: Path | str | None = None,
    overwrite_main: bool | None = None,
) -> list[WriteResult]:
    """Scaffold packaging/buildozer/buildozer.spec."""
    target_dir = Path(root_dir) if root_dir else Path.cwd()

    meta = resolve_buildozer_metadata(
        target_dir / "pyproject.toml"
    )

    buildozer_dir = target_dir / "packaging" / "buildozer"
    buildozer_dir.mkdir(parents=True, exist_ok=True)

    spec_path = buildozer_dir / "buildozer.spec"

    result = write_str_to_file(
        path=spec_path,
        text=BUILDOZER_SPEC_TEMPLATE.format(**meta),
    )
    
    # also copy src/*/__main__.py to main.py
    copy_source_dunder_main_to_root_main_for_buildozer_entry_point(overwrite=overwrite_main)

    return [result]

