# src/maxson_build_utils/scaffold/packaging/buildozer.py
from __future__ import annotations

from pathlib import Path

from ...helpers import WriteResult, write_str_to_file
from ...names import to_title_case
from ...pyproject import MaxsonPyProject


BUILDOZER_SPEC_TEMPLATE = """\
# This .spec config file tells Buildozer an app's requirements for being built.
#
# It is generated by maxson-build-utils.
# Edit this file for Buildozer-specific packaging requirements.

[app]

# (str) Title of your application
title = {APP_TITLE}

# (str) Package name
package.name = {PACKAGE_NAME}

# (str) Package domain (needed for Android/iOS packaging)
package.domain = {PACKAGE_DOMAIN}

# (str) Source code where the main.py lives
source.dir = ../../

# (list) Source files to include
source.include_exts = py,png,jpg,kv,atlas,whl,wsdl,json

# (list) Source files to include using pattern matching
source.include_patterns = src/*,vendor_for_buildozer/*

# (list) Source directories to exclude
source.exclude_dirs = tests,bin,.git,.venv,.pytest_cache,docs,logs,packaging

# (list) Source patterns to exclude
source.exclude_patterns = Dockerfile*,build_*.py,package.py,daemon_*.py

# (str) Application version
version = {VERSION}

# (list) Application requirements
#
# Keep this deliberately small. Dependencies that do not have
# Buildozer/python-for-android recipes can be vendored separately.
requirements = hostpython3==3.11.9,python3==3.11.9,kivy,pyjnius

# (str) Presplash
# presplash.filename = %(source.dir)s/data/presplash.png

# (str) Icon
# icon.filename = %(source.dir)s/src/{IMPORT_NAME}/data/icons/placeholder.png

# (str) Orientation
orientation = portrait

# (bool) Whether to fullscreen
fullscreen = 0


[buildozer]

# (str) Logging level
log_level = 2


[buildozer]

# (str) Warning: Buildozer configuration can be extended here as needed.
"""


def resolve_buildozer_metadata(
    path: Path | str | None = None,
) -> dict[str, str]:
    pyproject = MaxsonPyProject(path)

    import_name = pyproject.import_name
    app_name = pyproject.app_name

    package_name = (
        pyproject.get(
            "tool",
            "maxson-build-utils",
            "buildozer",
            "package-name",
        )
        or import_name
    )

    package_domain = (
        pyproject.get(
            "tool",
            "maxson-build-utils",
            "buildozer",
            "package-domain",
        )
        or "com.memphis_wastewater"
    )

    version = (
        pyproject.get(
            "project",
            "version",
        )
        or "0.1"
    )

    return {
        "APP_TITLE": to_title_case(app_name),
        "PACKAGE_NAME": package_name,
        "PACKAGE_DOMAIN": package_domain,
        "IMPORT_NAME": import_name,
        "VERSION": version,
    }


def run_init_buildozer(
    root_dir: Path | str | None = None,
) -> list[WriteResult]:
    """Scaffold packaging/buildozer/buildozer.spec."""
    target_dir = Path(root_dir) if root_dir else Path.cwd()

    meta = resolve_buildozer_metadata(
        target_dir / "pyproject.toml"
    )

    buildozer_dir = target_dir / "packaging" / "buildozer"
    buildozer_dir.mkdir(parents=True, exist_ok=True)

    spec_path = buildozer_dir / "buildozer.spec"

    result = write_str_to_file(
        path=spec_path,
        text=BUILDOZER_SPEC_TEMPLATE.format(**meta),
    )

    return [result]

