# This .spec config file tells Buildozer an app's requirements for being built.
#
# It is generated by maxson-build-utils.
# Edit this file for Buildozer-specific packaging requirements.

[app]

# (str) Title of your application
title = Maxson Build Utils

# (str) Package name
package.name = maxson_build_utils

# (str) Package domain (needed for Android/iOS packaging)
package.domain = com.memphis_wastewater

# (str) Source code where the main.py lives
source.dir = ../../

# (list) Source files to include
source.include_exts = py,png,jpg,kv,atlas,whl,wsdl,json

# (list) Source files to include using pattern matching
source.include_patterns = src/*,vendor_for_buildozer/*

# (list) Source directories to exclude
source.exclude_dirs = tests,bin,.git,.venv,.pytest_cache,docs,logs,packaging

# (list) Source patterns to exclude
source.exclude_patterns = Dockerfile*,build_*.py,package.py,daemon_*.py

# (str) Application version
version = 0.1

# (list) Application requirements
#
# Keep this deliberately small. Dependencies that do not have
# Buildozer/python-for-android recipes can be vendored separately.
requirements = hostpython3==3.11.9,python3==3.11.9,kivy,pyjnius

# (str) Presplash
# presplash.filename = %(source.dir)s/data/presplash.png

# (str) Icon
# icon.filename = %(source.dir)s/src/maxson_build_utils/data/icons/placeholder.png

# (str) Orientation
orientation = portrait

# (bool) Whether to fullscreen
fullscreen = 0


[buildozer]

# (str) Logging level
log_level = 2


[buildozer]

# (str) Warning: Buildozer configuration can be extended here as needed.
