# This .spec config file tells Buildozer an app's requirements for being built.
#
# It is generated by maxson-build-utils.
# Edit this file for Buildozer-specific packaging requirements.

[app]

# (str) Title of your application
title = Maxson Build Utils

# (str) Package name
package.name = maxson_build_utils

# (str) Package domain (needed for Android/iOS packaging)
package.domain = com.memphis_wastewater

# (str) Source code where the main.py lives
source.dir = ../../

# (list) Source files to include
source.include_exts = py,png,jpg,kv,atlas,whl,wsdl,json

# (list) Source files to include using pattern matching
source.include_patterns = main.py,src/*,vendor/packages/*

# (list) Source directories to exclude
source.exclude_dirs = tests,bin,.git,.venv,.pytest_cache,docs,logs,packaging

# (list) Source patterns to exclude
source.exclude_patterns = Dockerfile*,build_*.py,package.py,daemon_*.py

# (str) Application version
#version = 0.1
version.filename = %(source.dir)s/src/pipeline_eds/VERSION
version.regex = (.*)

# (list) Application requirements
#
# Keep this deliberately small. Dependencies that do not have
# Buildozer/python-for-android recipes can be vendored separately.
requirements = hostpython3==3.11.9,python3==3.11.9,kivy,pyjnius

# (str) Presplash
# presplash.filename = %(source.dir)s/data/presplash.png

# (str) Icon
# icon.filename = %(source.dir)s/src/maxson_build_utils/data/icons/placeholder.png

# (str) Orientation
orientation = portrait


#
# OSX Specific
#

#
# author = © Copyright Info

# Kivy version to use
osx.kivy_version = 2.2.0

#
# Android specific
#

# (bool) Indicate if the application should be fullscreen or not
fullscreen = 0

# (str) Adaptive icon of the application (used if Android API level is 26+ at runtime)
#icon.adaptive_foreground.filename = %(source.dir)s/data/icon_fg.png
#icon.adaptive_background.filename = %(source.dir)s/data/icon_bg.png

# (list) Permissions
# (See https://python-for-android.readthedocs.io/en/latest/buildoptions.html for all the supported syntaxes and propert>
#android.permissions = android.permission.INTERNET, (name=android.permission.WRITE_EXTERNAL_STORAGE;maxSdkVersion=18)

# (list) features (adds uses-feature -tags to manifest)
#android.features = android.hardware.usb.host

# (int) Target Android API, should be as high as possible.
android.api = 34

# (int) Minimum API your APK / AAB will support.
android.minapi = 24

# (int) Android SDK version to use
#android.sdk = 20

# (str) Android NDK version to use
android.ndk = 25b

# (list) The Android archs to build for, choices: armeabi-v7a, arm64-v8a, x86, x86_64
# In past, was `android.arch` as we weren't supporting builds for multiple archs at the same time.
android.archs = arm64-v8a, armeabi-v7a

# (int) overrides automatic versionCode computation (used in build.gradle)
# this is not the same as app version and should only be edited if you know what you're doing
# android.numeric_version = 1

# (bool) enables Android auto backup feature (Android API >=23)
android.allow_backup = True

#
# Python for android (p4a) specific
#

# (str) python-for-android URL to use for checkout
#p4a.url =

# (str) python-for-android fork to use in case if p4a.url is not specified, defaults to upstream (kivy)
#p4a.fork = kivy

# (str) python-for-android branch to use, defaults to master
#p4a.branch = master
p4a.branch = v2024.01.21

# (str) python-for-android specific commit to use, defaults to HEAD, must be within p4a.branch
#p4a.commit = HEAD
p4a.commit = 957a3e5f


[buildozer]

# (str) Logging level
log_level = 2


# (str) Path to build artifact storage, absolute or relative to spec file
#build_dir = ../../build/buildozer
build_dir = ~/.buildozer_work/pipeline-eds/build

# (str) Path to build output (i.e. .apk, .aab, .ipa) storage
bin_dir = ../../dist/buildozer

# (str) Warning: Buildozer configuration can be extended here as needed.
