# This .spec config file tells Buildozer an app's requirements for being built.
#
# It is generated by maxson-build-utils.
# Edit this file for Buildozer-specific packaging requirements.

[app]

# (str) Title of your application
title = Maxson Build Utils

# (str) Package name
package.name = maxson_build_utils

# (str) Package domain (needed for Android/iOS packaging)
package.domain = com.memphis_wastewater.maxson_build_utils

# (str) Source code where the main.py lives
source.dir = ../../

# (list) Source files to include
source.include_exts = py,png,jpg,kv,atlas,whl,wsdl,json

# (list) Source files to include using pattern matching
#source.include_patterns = main.py,src/*,./vendor/site-packages/*
source.include_patterns = main.py,src/*,src/**/*,vendor/*, vendor/**/*, assets/*

# (list) Source directories to exclude
source.exclude_dirs = tests,bin,.git,.venv,.pytest_cache,docs,logs,packaging

# (list) Source patterns to exclude
source.exclude_patterns = Dockerfile*,build_*.py,package.py,daemon_*.py

# (str) Application version
version = 0.1

# (list) Application requirements
#
# Keep this deliberately small. Dependencies that do not have
# Buildozer/python-for-android recipes can be vendored separately.
requirements = hostpython3==3.11.9,python3==3.11.9,kivy,pyjnius

# (str) Presplash
# presplash.filename = %(source.dir)s/data/presplash.png

# (str) Icon
# icon.filename = %(source.dir)s/src/maxson_build_utils/data/icons/placeholder.png

# (str) Orientation
orientation = portrait

#
# OSX Specific
#

#
# author = © Copyright Info

# Kivy version to use
osx.kivy_version = 2.2.0

#
# Android specific
#

# (bool) Whether to fullscreen
fullscreen = 0

# (str) Adaptive icon of the application (used if Android API level is 26+ at runtime)
#icon.adaptive_foreground.filename = %(source.dir)s/data/icon_fg.png
#icon.adaptive_background.filename = %(source.dir)s/data/icon_bg.png

# (list) Permissions
# (See https://python-for-android.readthedocs.io/en/latest/buildoptions.html for all the supported syntaxes and propert>
#android.permissions = android.permission.INTERNET, (name=android.permission.WRITE_EXTERNAL_STORAGE;maxSdkVersion=18)

# (list) features (adds uses-feature -tags to manifest)
#android.features = android.hardware.usb.host

# (int) Target Android API, should be as high as possible.
android.api = 34

# (int) Minimum API your APK / AAB will support.
android.minapi = 24

# (int) Android SDK version to use
#android.sdk = 20

# (str) Android NDK version to use
android.ndk = 25b

# (int) Android NDK API to use. This is the minimum API your app will support, it should usually match android.minapi.
#android.ndk_api = 21

# (str) Android NDK directory (if empty, it will be automatically downloaded.)
#android.ndk_path =

# (str) Android SDK directory (if empty, it will be automatically downloaded.)
#android.sdk_path =

# (str) ANT directory (if empty, it will be automatically downloaded.)
#android.ant_path =

# (list) The Android archs to build for, choices: armeabi-v7a, arm64-v8a, x86, x86_64
# In past, was `android.arch` as we weren't supporting builds for multiple archs at the same time.
android.archs = arm64-v8a, armeabi-v7a

# (int) overrides automatic versionCode computation (used in build.gradle)
# this is not the same as app version and should only be edited if you know what you're doing
# android.numeric_version = 1

# (bool) enables Android auto backup feature (Android API >=23)
android.allow_backup = True

#
# Python for android (p4a) specific
#

# (str) python-for-android URL to use for checkout
#p4a.url =

# (str) python-for-android fork to use in case if p4a.url is not specified, defaults to upstream (kivy)
#p4a.fork = kivy

# (str) python-for-android branch to use, defaults to master
#p4a.branch = master
p4a.branch = v2024.01.21

# (str) python-for-android specific commit to use, defaults to HEAD, must be within p4a.branch
#p4a.commit = HEAD
p4a.commit = 957a3e5f

# (str) python-for-android git clone directory
#p4a.source_dir =

#
# iOS specific
#

# (str) Path to a custom kivy-ios folder
#ios.kivy_ios_dir = ../kivy-ios
# Alternately, specify the URL and branch of a git checkout:
ios.kivy_ios_url = https://github.com/kivy/kivy-ios
ios.kivy_ios_branch = master

# Another platform dependency: ios-deploy
# Uncomment to use a custom checkout
#ios.ios_deploy_dir = ../ios_deploy
# Or specify URL and branch
ios.ios_deploy_url = https://github.com/phonegap/ios-deploy
ios.ios_deploy_branch = 1.12.2

# (bool) Whether or not to sign the code
ios.codesign.allowed = false

[buildozer]

# (int) Log level (0 = error only, 1 = info, 2 = debug (with command output))
log_level = 2

# (int) Display warning if buildozer is run as root (0 = False, 1 = True)
warn_on_root = 1

# (str) Path to build artifact storage, absolute or relative to spec file
# build_dir = ../../build/buildozer/
build_dir = ~/.buildozer_work/maxson_build_utils/build/
# (str) Path to build output (i.e. .apk, .aab, .ipa) storage
bin_dir = ../../dist/buildozer/



# (str) Warning: Buildozer configuration can be extended here as needed.
